---
- symbol: 360ONE
  isin: INE466L01038
- symbol: 3MINDIA
  isin: INE470A01017
- symbol: AADHARHFC
  isin: INE883F01010
- symbol: AARTIIND
  isin: INE769A01020
- symbol: AAVAS
  isin: INE216P01012
- symbol: ABB
  isin: INE117A01022
- symbol: ABBOTINDIA
  isin: INE358A01014
- symbol: ABCAPITAL
  isin: INE674K01013
- symbol: ABFRL
  isin: INE647O01011
- symbol: ABLBL
  isin: INE14LE01019
- symbol: ABREL
  isin: INE055A01016
- symbol: ABSLAMC
  isin: INE404A01024
- symbol: ACC
  isin: INE012A01025
- symbol: ACE
  isin: INE731H01025
- symbol: ACMESOLAR
  isin: INE622W01025
- symbol: ADANIENSOL
  isin: INE931S01010
- symbol: ADANIENT
  isin: INE423A01024
- symbol: ADANIGREEN
  isin: INE364U01010
- symbol: ADANIPORTS
  isin: INE742F01042
- symbol: ADANIPOWER
  isin: INE814H01029
- symbol: AEGISLOG
  isin: INE208C01025
- symbol: AEGISVOPAK
  isin: INE0INX01018
- symbol: AFCONS
  isin: INE101I01011
- symbol: AFFLE
  isin: INE00WC01027
- symbol: AGARWALEYE
  isin: INE943P01029
- symbol: AIAENG
  isin: INE212H01026
- symbol: AIIL
  isin: INE206F01022
- symbol: AJANTPHARM
  isin: INE031B01049
- symbol: AKUMS
  isin: INE09XN01023
- symbol: AKZOINDIA
  isin: INE133A01011
- symbol: ALKEM
  isin: INE540L01014
- symbol: ALKYLAMINE
  isin: INE150B01039
- symbol: ALOKINDS
  isin: INE270A01029
- symbol: AMBER
  isin: INE371P01015
- symbol: AMBUJACEM
  isin: INE079A01024
- symbol: ANANDRATHI
  isin: INE463V01026
- symbol: ANANTRAJ
  isin: INE242C01024
- symbol: ANGELONE
  isin: INE732I01013
- symbol: APARINDS
  isin: INE372A01015
- symbol: APLAPOLLO
  isin: INE702C01027
- symbol: APLLTD
  isin: INE901L01018
- symbol: APOLLOHOSP
  isin: INE437A01024
- symbol: APOLLOTYRE
  isin: INE438A01022
- symbol: APTUS
  isin: INE852O01025
- symbol: ARE&M
  isin: INE885A01032
- symbol: ASAHIINDIA
  isin: INE439A01020
- symbol: ASHOKLEY
  isin: INE208A01029
- symbol: ASIANPAINT
  isin: INE021A01026
- symbol: ASTERDM
  isin: INE914M01019
- symbol: ASTRAL
  isin: INE006I01046
- symbol: ASTRAZEN
  isin: INE203A01020
- symbol: ATGL
  isin: INE399L01023
- symbol: ATHERENERG
  isin: INE0LEZ01016
- symbol: ATUL
  isin: INE100A01010
- symbol: AUBANK
  isin: INE949L01017
- symbol: AUROPHARMA
  isin: INE406A01037
- symbol: AWL
  isin: INE699H01024
- symbol: AXISBANK
  isin: INE238A01034
- symbol: BAJAJ-AUTO
  isin: INE917I01010
- symbol: BAJAJFINSV
  isin: INE918I01026
- symbol: BAJAJHFL
  isin: INE377Y01014
- symbol: BAJAJHLDNG
  isin: INE118A01012
- symbol: BAJFINANCE
  isin: INE296A01032
- symbol: BALKRISIND
  isin: INE787D01026
- symbol: BALRAMCHIN
  isin: INE119A01028
- symbol: BANDHANBNK
  isin: INE545U01014
- symbol: BANKBARODA
  isin: INE028A01039
- symbol: BANKINDIA
  isin: INE084A01016
- symbol: BANKNIFTY
  isin: 
- symbol: BASF
  isin: INE373A01013
- symbol: BATAINDIA
  isin: INE176A01028
- symbol: BAYERCROP
  isin: INE462A01022
- symbol: BBTC
  isin: INE050A01025
- symbol: BDL
  isin: INE171Z01026
- symbol: BEL
  isin: INE263A01024
- symbol: BEML
  isin: INE258A01024
- symbol: BERGEPAINT
  isin: INE463A01038
- symbol: BHARATFORG
  isin: INE465A01025
- symbol: BHARTIARTL
  isin: INE397D01024
- symbol: BHARTIHEXA
  isin: INE343G01021
- symbol: BHEL
  isin: INE257A01026
- symbol: BIKAJI
  isin: INE00E101023
- symbol: BIOCON
  isin: INE376G01013
- symbol: BLS
  isin: INE153T01027
- symbol: BLUEDART
  isin: INE233B01017
- symbol: BLUEJET
  isin: INE0KBH01020
- symbol: BLUESTARCO
  isin: INE472A01039
- symbol: BOSCHLTD
  isin: INE323A01026
- symbol: BPCL
  isin: INE029A01011
- symbol: BRIGADE
  isin: INE791I01019
- symbol: BRITANNIA
  isin: INE216A01030
- symbol: BSE
  isin: INE118H01025
- symbol: BSOFT
  isin: INE836A01035
- symbol: CAMPUS
  isin: INE278Y01022
- symbol: CAMS
  isin: INE596I01020
- symbol: CANBK
  isin: INE476A01022
- symbol: CANFINHOME
  isin: INE477A01020
- symbol: CAPLIPOINT
  isin: INE475E01026
- symbol: CARBORUNIV
  isin: INE120A01034
- symbol: CASTROLIND
  isin: INE172A01027
- symbol: CCL
  isin: INE421D01022
- symbol: CDSL
  isin: INE736A01011
- symbol: CEATLTD
  isin: INE482A01020
- symbol: CENTRALBK
  isin: INE483A01010
- symbol: CENTURYPLY
  isin: INE348B01021
- symbol: CERA
  isin: INE739E01017
- symbol: CESC
  isin: INE486A01021
- symbol: CGCL
  isin: INE180C01042
- symbol: CGPOWER
  isin: INE067A01029
- symbol: CHALET
  isin: INE427F01016
- symbol: CHAMBLFERT
  isin: INE085A01013
- symbol: CHENNPETRO
  isin: INE178A01016
- symbol: CHOICEIN
  isin: INE102B01014
- symbol: CHOLAFIN
  isin: INE121A01024
- symbol: CHOLAHLDNG
  isin: INE149A01033
- symbol: CIPLA
  isin: INE059A01026
- symbol: CLEAN
  isin: INE227W01023
- symbol: COALINDIA
  isin: INE522F01014
- symbol: COCHINSHIP
  isin: INE704P01025
- symbol: COFORGE
  isin: INE591G01025
- symbol: COHANCE
  isin: INE03QK01018
- symbol: COLPAL
  isin: INE259A01022
- symbol: CONCOR
  isin: INE111A01025
- symbol: CONCORDBIO
  isin: INE338H01029
- symbol: COROMANDEL
  isin: INE169A01031
- symbol: CRAFTSMAN
  isin: INE00LO01017
- symbol: CREDITACC
  isin: INE741K01010
- symbol: CRISIL
  isin: INE007A01025
- symbol: CROMPTON
  isin: INE299U01018
- symbol: CUB
  isin: INE491A01021
- symbol: CUMMINSIND
  isin: INE298A01020
- symbol: CYIENT
  isin: INE136B01020
- symbol: DABUR
  isin: INE016A01026
- symbol: DALBHARAT
  isin: INE00R701025
- symbol: DATAPATTNS
  isin: INE0IX101010
- symbol: DBREALTY
  isin: INE879I01012
- symbol: DCMSHRIRAM
  isin: INE499A01024
- symbol: DEEPAKFERT
  isin: INE501A01019
- symbol: DEEPAKNTR
  isin: INE288B01029
- symbol: DELHIVERY
  isin: INE148O01028
- symbol: DEVYANI
  isin: INE872J01023
- symbol: DIVISLAB
  isin: INE361B01024
- symbol: DIXON
  isin: INE935N01020
- symbol: DLF
  isin: INE271C01023
- symbol: DMART
  isin: INE192R01011
- symbol: DOMS
  isin: INE321T01012
- symbol: DRREDDY
  isin: INE089A01031
- symbol: DUMMYHDLVR
  isin: DUM030A01027
- symbol: ECLERX
  isin: INE738I01010
- symbol: EICHERMOT
  isin: INE066A01021
- symbol: EIDPARRY
  isin: INE126A01031
- symbol: EIHOTEL
  isin: INE230A01023
- symbol: ELECON
  isin: INE205B01031
- symbol: ELGIEQUIP
  isin: INE285A01027
- symbol: EMAMILTD
  isin: INE548C01032
- symbol: EMCURE
  isin: INE168P01015
- symbol: ENDURANCE
  isin: INE913H01037
- symbol: ENGINERSIN
  isin: INE510A01028
- symbol: ENRIN
  isin: INE1NPP01017
- symbol: ERIS
  isin: INE406M01024
- symbol: ESCORTS
  isin: INE042A01014
- symbol: ETERNAL
  isin: INE758T01015
- symbol: EXIDEIND
  isin: INE302A01020
- symbol: FACT
  isin: INE188A01015
- symbol: FEDERALBNK
  isin: INE171A01029
- symbol: FINCABLES
  isin: INE235A01022
- symbol: FINPIPE
  isin: INE183A01024
- symbol: FIRSTCRY
  isin: INE02RE01045
- symbol: FIVESTAR
  isin: INE128S01021
- symbol: FLUOROCHEM
  isin: INE09N301011
- symbol: FORCEMOT
  isin: INE451A01017
- symbol: FORTIS
  isin: INE061F01013
- symbol: FSL
  isin: INE684F01012
- symbol: GAIL
  isin: INE129A01019
- symbol: GESHIP
  isin: INE017A01032
- symbol: GICRE
  isin: INE481Y01014
- symbol: GILLETTE
  isin: INE322A01010
- symbol: GLAND
  isin: INE068V01023
- symbol: GLAXO
  isin: INE159A01016
- symbol: GLENMARK
  isin: INE935A01035
- symbol: GMDCLTD
  isin: INE131A01031
- symbol: GMRAIRPORT
  isin: INE776C01039
- symbol: GODFRYPHLP
  isin: INE260B01028
- symbol: GODIGIT
  isin: INE03JT01014
- symbol: GODREJAGRO
  isin: INE850D01014
- symbol: GODREJCP
  isin: INE102D01028
- symbol: GODREJIND
  isin: INE233A01035
- symbol: GODREJPROP
  isin: INE484J01027
- symbol: GPIL
  isin: INE177H01039
- symbol: GRANULES
  isin: INE101D01020
- symbol: GRAPHITE
  isin: INE371A01025
- symbol: GRASIM
  isin: INE047A01021
- symbol: GRAVITA
  isin: INE024L01027
- symbol: GRSE
  isin: INE382Z01011
- symbol: GSPL
  isin: INE246F01010
- symbol: GUJGASLTD
  isin: INE844O01030
- symbol: GVT&D
  isin: INE200A01026
- symbol: HAL
  isin: INE066F01020
- symbol: HAPPSTMNDS
  isin: INE419U01012
- symbol: HAVELLS
  isin: INE176B01034
- symbol: HBLENGINE
  isin: INE292B01021
- symbol: HCLTECH
  isin: INE860A01027
- symbol: HDFCAMC
  isin: INE127D01025
- symbol: HDFCBANK
  isin: INE040A01034
- symbol: HDFCLIFE
  isin: INE795G01014
- symbol: HEG
  isin: INE545A01024
- symbol: HEROMOTOCO
  isin: INE158A01026
- symbol: HEXT
  isin: INE093A01041
- symbol: HFCL
  isin: INE548A01028
- symbol: HINDALCO
  isin: INE038A01020
- symbol: HINDCOPPER
  isin: INE531E01026
- symbol: HINDPETRO
  isin: INE094A01015
- symbol: HINDUNILVR
  isin: INE030A01027
- symbol: HINDZINC
  isin: INE267A01025
- symbol: HOMEFIRST
  isin: INE481N01025
- symbol: HONASA
  isin: INE0J5401028
- symbol: HONAUT
  isin: INE671A01010
- symbol: HSCL
  isin: INE019C01026
- symbol: HUDCO
  isin: INE031A01017
- symbol: HYUNDAI
  isin: INE0V6F01027
- symbol: ICICIBANK
  isin: INE090A01021
- symbol: ICICIGI
  isin: INE765G01017
- symbol: ICICIPRULI
  isin: INE726G01019
- symbol: IDBI
  isin: INE008A01015
- symbol: IDEA
  isin: INE669E01016
- symbol: IDFCFIRSTB
  isin: INE092T01019
- symbol: IEX
  isin: INE022Q01020
- symbol: IFCI
  isin: INE039A01010
- symbol: IGIL
  isin: INE0Q9301021
- symbol: IGL
  isin: INE203G01027
- symbol: IIFL
  isin: INE530B01024
- symbol: IKS
  isin: INE115Q01022
- symbol: INDGN
  isin: INE065X01017
- symbol: INDHOTEL
  isin: INE053A01029
- symbol: INDIACEM
  isin: INE383A01012
- symbol: INDIAMART
  isin: INE933S01016
- symbol: INDIANB
  isin: INE562A01011
- symbol: INDIGO
  isin: INE646L01027
- symbol: INDUSINDBK
  isin: INE095A01012
- symbol: INDUSTOWER
  isin: INE121J01017
- symbol: INFY
  isin: INE009A01021
- symbol: INOXINDIA
  isin: INE616N01034
- symbol: INOXWIND
  isin: INE066P01011
- symbol: INTELLECT
  isin: INE306R01017
- symbol: IOB
  isin: INE565A01014
- symbol: IOC
  isin: INE242A01010
- symbol: IPCALAB
  isin: INE571A01038
- symbol: IRB
  isin: INE821I01022
- symbol: IRCON
  isin: INE962Y01021
- symbol: IRCTC
  isin: INE335Y01020
- symbol: IREDA
  isin: INE202E01016
- symbol: IRFC
  isin: INE053F01010
- symbol: ITC
  isin: INE154A01025
- symbol: ITCHOTELS
  isin: INE379A01028
- symbol: ITI
  isin: INE248A01017
- symbol: J&KBANK
  isin: INE168A01041
- symbol: JBCHEPHARM
  isin: INE572A01036
- symbol: JBMA
  isin: INE927D01051
- symbol: JINDALSAW
  isin: INE324A01032
- symbol: JINDALSTEL
  isin: INE749A01030
- symbol: JIOFIN
  isin: INE758E01017
- symbol: JKCEMENT
  isin: INE823G01014
- symbol: JKTYRE
  isin: INE573A01042
- symbol: JMFINANCIL
  isin: INE780C01023
- symbol: JPPOWER
  isin: INE351F01018
- symbol: JSL
  isin: INE220G01021
- symbol: JSWENERGY
  isin: INE121E01018
- symbol: JSWINFRA
  isin: INE880J01026
- symbol: JSWSTEEL
  isin: INE019A01038
- symbol: JUBLFOOD
  isin: INE797F01020
- symbol: JUBLINGREA
  isin: INE0BY001018
- symbol: JUBLPHARMA
  isin: INE700A01033
- symbol: JWL
  isin: INE209L01016
- symbol: JYOTHYLAB
  isin: INE668F01031
- symbol: JYOTICNC
  isin: INE980O01024
- symbol: KAJARIACER
  isin: INE217B01036
- symbol: KALYANKJIL
  isin: INE303R01014
- symbol: KARURVYSYA
  isin: INE036D01028
- symbol: KAYNES
  isin: INE918Z01012
- symbol: KEC
  isin: INE389H01022
- symbol: KEI
  isin: INE878B01027
- symbol: KFINTECH
  isin: INE138Y01010
- symbol: KIMS
  isin: INE967H01025
- symbol: KIRLOSBROS
  isin: INE732A01036
- symbol: KIRLOSENG
  isin: INE146L01010
- symbol: KOTAKBANK
  isin: INE237A01028
- symbol: KPIL
  isin: INE220B01022
- symbol: KPITTECH
  isin: INE04I401011
- symbol: KPRMILL
  isin: INE930H01031
- symbol: KSB
  isin: INE999A01023
- symbol: LALPATHLAB
  isin: INE600L01024
- symbol: LATENTVIEW
  isin: INE0I7C01011
- symbol: LAURUSLABS
  isin: INE947Q01028
- symbol: LEMONTREE
  isin: INE970X01018
- symbol: LICHSGFIN
  isin: INE115A01026
- symbol: LICI
  isin: INE0J1Y01017
- symbol: LINDEINDIA
  isin: INE473A01011
- symbol: LLOYDSME
  isin: INE281B01032
- symbol: LODHA
  isin: INE670K01029
- symbol: LT
  isin: INE018A01030
- symbol: LTF
  isin: INE498L01015
- symbol: LTFOODS
  isin: INE818H01020
- symbol: LTIM
  isin: INE214T01019
- symbol: LTTS
  isin: INE010V01017
- symbol: LUPIN
  isin: INE326A01037
- symbol: M&M
  isin: INE101A01026
- symbol: M&MFIN
  isin: INE774D01024
- symbol: MAHABANK
  isin: INE457A01014
- symbol: MAHSCOOTER
  isin: INE288A01013
- symbol: MAHSEAMLES
  isin: INE271B01025
- symbol: MANAPPURAM
  isin: INE522D01027
- symbol: MANKIND
  isin: INE634S01028
- symbol: MANYAVAR
  isin: INE825V01034
- symbol: MAPMYINDIA
  isin: INE0BV301023
- symbol: MARICO
  isin: INE196A01026
- symbol: MARUTI
  isin: INE585B01010
- symbol: MAXHEALTH
  isin: INE027H01010
- symbol: MAZDOCK
  isin: INE249Z01020
- symbol: MCX
  isin: INE745G01035
- symbol: MEDANTA
  isin: INE474Q01031
- symbol: METROPOLIS
  isin: INE112L01020
- symbol: MFSL
  isin: INE180A01020
- symbol: MGL
  isin: INE002S01010
- symbol: MINDACORP
  isin: INE842C01021
- symbol: MMTC
  isin: INE123F01029
- symbol: MOTHERSON
  isin: INE775A01035
- symbol: MOTILALOFS
  isin: INE338I01027
- symbol: MPHASIS
  isin: INE356A01018
- symbol: MRF
  isin: INE883A01011
- symbol: MRPL
  isin: INE103A01014
- symbol: MSUMI
  isin: INE0FS801015
- symbol: MUTHOOTFIN
  isin: INE414G01012
- symbol: NAM-INDIA
  isin: INE298J01013
- symbol: NATCOPHARM
  isin: INE987B01026
- symbol: NATIONALUM
  isin: INE139A01034
- symbol: NAUKRI
  isin: INE663F01032
- symbol: NAVA
  isin: INE725A01030
- symbol: NAVINFLUOR
  isin: INE048G01026
- symbol: NBCC
  isin: INE095N01031
- symbol: NCC
  isin: INE868B01028
- symbol: NESTLEIND
  isin: INE239A01024
- symbol: NETWEB
  isin: INE0NT901020
- symbol: NEULANDLAB
  isin: INE794A01010
- symbol: NEWGEN
  isin: INE619B01017
- symbol: NH
  isin: INE410P01011
- symbol: NHPC
  isin: INE848E01016
- symbol: NIACL
  isin: INE470Y01017
- symbol: NIFTY
  isin: 
- symbol: NIVABUPA
  isin: INE995S01015
- symbol: NLCINDIA
  isin: INE589A01014
- symbol: NMDC
  isin: INE584A01023
- symbol: NSLNISP
  isin: INE0NNS01018
- symbol: NTPC
  isin: INE733E01010
- symbol: NTPCGREEN
  isin: INE0ONG01011
- symbol: NUVAMA
  isin: INE531F01015
- symbol: NUVOCO
  isin: INE118D01016
- symbol: NYKAA
  isin: INE388Y01029
- symbol: OBEROIRLTY
  isin: INE093I01010
- symbol: OFSS
  isin: INE881D01027
- symbol: OIL
  isin: INE274J01014
- symbol: OLAELEC
  isin: INE0LXG01040
- symbol: OLECTRA
  isin: INE260D01016
- symbol: ONESOURCE
  isin: INE013P01021
- symbol: ONGC
  isin: INE213A01029
- symbol: PAGEIND
  isin: INE761H01022
- symbol: PATANJALI
  isin: INE619A01035
- symbol: PAYTM
  isin: INE982J01020
- symbol: PCBL
  isin: INE602A01031
- symbol: PERSISTENT
  isin: INE262H01021
- symbol: PETRONET
  isin: INE347G01014
- symbol: PFC
  isin: INE134E01011
- symbol: PFIZER
  isin: INE182A01018
- symbol: PGEL
  isin: INE457L01029
- symbol: PGHH
  isin: INE179A01014
- symbol: PHOENIXLTD
  isin: INE211B01039
- symbol: PIDILITIND
  isin: INE318A01026
- symbol: PIIND
  isin: INE603J01030
- symbol: PNB
  isin: INE160A01022
- symbol: PNBHOUSING
  isin: INE572E01012
- symbol: POLICYBZR
  isin: INE417T01026
- symbol: POLYCAB
  isin: INE455K01017
- symbol: POLYMED
  isin: INE205C01021
- symbol: POONAWALLA
  isin: INE511C01022
- symbol: POWERGRID
  isin: INE752E01010
- symbol: POWERINDIA
  isin: INE07Y701011
- symbol: PPLPHARMA
  isin: INE0DK501011
- symbol: PRAJIND
  isin: INE074A01025
- symbol: PREMIERENE
  isin: INE0BS701011
- symbol: PRESTIGE
  isin: INE811K01011
- symbol: PTCIL
  isin: INE596F01018
- symbol: PVRINOX
  isin: INE191H01014
- symbol: RADICO
  isin: INE944F01028
- symbol: RAILTEL
  isin: INE0DD101019
- symbol: RAINBOW
  isin: INE961O01016
- symbol: RAMCOCEM
  isin: INE331A01037
- symbol: RBLBANK
  isin: INE976G01028
- symbol: RCF
  isin: INE027A01015
- symbol: RECLTD
  isin: INE020B01018
- symbol: REDINGTON
  isin: INE891D01026
- symbol: RELIANCE
  isin: INE002A01018
- symbol: RELINFRA
  isin: INE036A01016
- symbol: RHIM
  isin: INE743M01012
- symbol: RITES
  isin: INE320J01015
- symbol: RKFORGE
  isin: INE399G01023
- symbol: RPOWER
  isin: INE614G01033
- symbol: RRKABEL
  isin: INE777K01022
- symbol: RVNL
  isin: INE415G01027
- symbol: SAGILITY
  isin: INE0W2G01015
- symbol: SAIL
  isin: INE114A01011
- symbol: SAILIFE
  isin: INE570L01029
- symbol: SAMMAANCAP
  isin: INE148I01020
- symbol: SAPPHIRE
  isin: INE806T01020
- symbol: SARDAEN
  isin: INE385C01021
- symbol: SAREGAMA
  isin: INE979A01025
- symbol: SBFC
  isin: INE423Y01016
- symbol: SBICARD
  isin: INE018E01016
- symbol: SBILIFE
  isin: INE123W01016
- symbol: SBIN
  isin: INE062A01020
- symbol: SCHAEFFLER
  isin: INE513A01022
- symbol: SCHNEIDER
  isin: INE839M01018
- symbol: SCI
  isin: INE109A01011
- symbol: SHREECEM
  isin: INE070A01015
- symbol: SHRIRAMFIN
  isin: INE721A01047
- symbol: SHYAMMETL
  isin: INE810G01011
- symbol: SIEMENS
  isin: INE003A01024
- symbol: SIGNATURE
  isin: INE903U01023
- symbol: SJVN
  isin: INE002L01015
- symbol: SKFINDIA
  isin: INE640A01023
- symbol: SOBHA
  isin: INE671H01015
- symbol: SOLARINDS
  isin: INE343H01029
- symbol: SONACOMS
  isin: INE073K01018
- symbol: SONATSOFTW
  isin: INE269A01021
- symbol: SRF
  isin: INE647A01010
- symbol: STARHEALTH
  isin: INE575P01011
- symbol: SUMICHEM
  isin: INE258G01013
- symbol: SUNDARMFIN
  isin: INE660A01013
- symbol: SUNDRMFAST
  isin: INE387A01021
- symbol: SUNPHARMA
  isin: INE044A01036
- symbol: SUNTV
  isin: INE424H01027
- symbol: SUPREMEIND
  isin: INE195A01028
- symbol: SUZLON
  isin: INE040H01021
- symbol: SWANCORP
  isin: INE665A01038
- symbol: SWIGGY
  isin: INE00H001014
- symbol: SYNGENE
  isin: INE398R01022
- symbol: SYRMA
  isin: INE0DYJ01015
- symbol: TARIL
  isin: INE763I01026
- symbol: TATACHEM
  isin: INE092A01019
- symbol: TATACOMM
  isin: INE151A01013
- symbol: TATACONSUM
  isin: INE192A01025
- symbol: TATAELXSI
  isin: INE670A01012
- symbol: TATAINVEST
  isin: INE672A01026
- symbol: TATAPOWER
  isin: INE245A01021
- symbol: TATASTEEL
  isin: INE081A01020
- symbol: TATATECH
  isin: INE142M01025
- symbol: TBOTEK
  isin: INE673O01025
- symbol: TCS
  isin: INE467B01029
- symbol: TECHM
  isin: INE669C01036
- symbol: TECHNOE
  isin: INE285K01026
- symbol: TEJASNET
  isin: INE010J01012
- symbol: THELEELA
  isin: INE0AQ201015
- symbol: THERMAX
  isin: INE152A01029
- symbol: TIINDIA
  isin: INE974X01010
- symbol: TIMKEN
  isin: INE325A01013
- symbol: TITAGARH
  isin: INE615H01020
- symbol: TITAN
  isin: INE280A01028
- symbol: TMPV
  isin: INE155A01022
- symbol: TORNTPHARM
  isin: INE685A01028
- symbol: TORNTPOWER
  isin: INE813H01021
- symbol: TRENT
  isin: INE849A01020
- symbol: TRIDENT
  isin: INE064C01022
- symbol: TRITURBINE
  isin: INE152M01016
- symbol: TRIVENI
  isin: INE256C01024
- symbol: TTML
  isin: INE517B01013
- symbol: TVSMOTOR
  isin: INE494B01023
- symbol: UBL
  isin: INE686F01025
- symbol: UCOBANK
  isin: INE691A01018
- symbol: ULTRACEMCO
  isin: INE481G01011
- symbol: UNIONBANK
  isin: INE692A01016
- symbol: UNITDSPR
  isin: INE854D01024
- symbol: UNOMINDA
  isin: INE405E01023
- symbol: UPL
  isin: INE628A01036
- symbol: USHAMART
  isin: INE228A01035
- symbol: UTIAMC
  isin: INE094J01016
- symbol: VBL
  isin: INE200M01039
- symbol: VEDL
  isin: INE205A01025
- symbol: VENTIVE
  isin: INE781S01027
- symbol: VGUARD
  isin: INE951I01027
- symbol: VIJAYA
  isin: INE043W01024
- symbol: VMM
  isin: INE01EA01019
- symbol: VOLTAS
  isin: INE226A01021
- symbol: VTL
  isin: INE825A01020
- symbol: WAAREEENER
  isin: INE377N01017
- symbol: WELCORP
  isin: INE191B01025
- symbol: WELSPUNLIV
  isin: INE192B01031
- symbol: WHIRLPOOL
  isin: INE716A01013
- symbol: WIPRO
  isin: INE075A01022
- symbol: WOCKPHARMA
  isin: INE049B01025
- symbol: YESBANK
  isin: INE528G01035
- symbol: ZEEL
  isin: INE256A01028
- symbol: ZENSARTECH
  isin: INE520A01027
- symbol: ZENTEC
  isin: INE251B01027
- symbol: ZFCVINDIA
  isin: INE342J01019
- symbol: ZYDUSLIFE
  isin: INE010B01027
